// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADbtDXpQCDHH0ayx48tJ7CqDZ6wgLR5o0',
    appId: '1:119269551240:web:d3cd44688a5e0d2355033d',
    messagingSenderId: '119269551240',
    projectId: 'ajay-8991b',
    authDomain: 'ajay-8991b.firebaseapp.com',
    databaseURL: 'https://ajay-8991b-default-rtdb.firebaseio.com',
    storageBucket: 'ajay-8991b.firebasestorage.app',
    measurementId: 'G-DNX6XER3L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsERr8q6f-1QiOYWszPYWniIZ8KegWNq4',
    appId: '1:119269551240:android:3305664b8ba2119e55033d',
    messagingSenderId: '119269551240',
    projectId: 'ajay-8991b',
    databaseURL: 'https://ajay-8991b-default-rtdb.firebaseio.com',
    storageBucket: 'ajay-8991b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdjf3wHH5UIQbRQM54pUpRk_PvboJlXRs',
    appId: '1:119269551240:ios:ad631bcf27d1eb6c55033d',
    messagingSenderId: '119269551240',
    projectId: 'ajay-8991b',
    databaseURL: 'https://ajay-8991b-default-rtdb.firebaseio.com',
    storageBucket: 'ajay-8991b.firebasestorage.app',
    iosBundleId: 'com.example.cardConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdjf3wHH5UIQbRQM54pUpRk_PvboJlXRs',
    appId: '1:119269551240:ios:ad631bcf27d1eb6c55033d',
    messagingSenderId: '119269551240',
    projectId: 'ajay-8991b',
    databaseURL: 'https://ajay-8991b-default-rtdb.firebaseio.com',
    storageBucket: 'ajay-8991b.firebasestorage.app',
    iosBundleId: 'com.example.cardConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADbtDXpQCDHH0ayx48tJ7CqDZ6wgLR5o0',
    appId: '1:119269551240:web:58f21f31fd95495955033d',
    messagingSenderId: '119269551240',
    projectId: 'ajay-8991b',
    authDomain: 'ajay-8991b.firebaseapp.com',
    databaseURL: 'https://ajay-8991b-default-rtdb.firebaseio.com',
    storageBucket: 'ajay-8991b.firebasestorage.app',
    measurementId: 'G-Z0X5ZF6TLJ',
  );
}
